deploy: 
  service:
    servicePort: 8080

deploy1: 
  ReplicaNumber: 1

  argocd:
    syncwave: 
      deployment: 5
      configmap: 1

  containers:
    containerPort: 8080
    image: 'quay.io/shachar_green/helloworldapp'
    tag: 'chart_v1'

  service:
      servicePort: 8080

deploy2: 
  ReplicaNumber: 1

  argocd:
    syncwave: 
      deployment: 10
      configmap: 1

  containers:
    containerPort: 8080
    image: 'quay.io/shachar_green/helloworldapp'
    tag: 'chart_v1'

  service:
    servicePort: 8080