test: Healthy

github:
  user: Shachar-Green
  token: empty-pass
  url: <https://api.github.com/repos/Shachar-Green/app-dev-repo/issues>

deploy: 
  service:
    servicePort: 8080

deploy1: 
  ReplicaNumber: 1

  argocd:
    syncwave: 
      deployment: 20
      configmap: 1

  containers:
    containerPort: 8080
    image: 'quay.io/shachar_green/helloworldapp'
    tag: 'chart_v1'

  service:
      servicePort: 8080

deploy2: 
  ReplicaNumber: 1

  argocd:
    syncwave: 
      deployment: 15
      configmap: 1

  containers:
    containerPort: 8080
    image: 'quay.io/shachar_green/helloworldapp'
    tag: 'chart_v1'

  service:
    servicePort: 8080