ReplicaNumber: 1

argocd:
  syncwave: 
    deployment: 5
    configmap: 1

containers:
  containerPort: 8080
  image: 'quay.io/shachar_green/helloworldapp'
  tag: 'chart_v1'

service:
  servicePort: 8080

probes:
  readiness:
    path: /health/liveliness
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    path: /health/liveliness
    initialDelaySeconds: 1
    timeoutSeconds: 1 
    periodSeconds: 10 
    successThreshold: 1  
    failureThreshold: 3
volume:
  mount:
    path: /tmp/html
